### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ShayanKhodadadian** [olyaee/anki_assist_ai#1]
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22635

When loading German with AudioTTS and Image OpenAI API Key Required:
Traceback (most recent call last):
  File "aqt.addons", line 250, in loadAddons
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\__init__.py", line 1, in <module>
    from .main import setup_menu
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\main.py", line 14, in <module>
    from .utils.example_generator import TranslationWorker, TTSWorker, ImageWorker
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\utils\example_generator.py", line 1, in <module>
    import openai
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\libs\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\libs\openai\types\__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\libs\openai\types\batch.py", line 7, in <module>
    from .._models import BaseModel
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\libs\openai\_models.py", line 24, in <module>
    from pydantic.fields import FieldInfo
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\libs\pydantic\fields.py", line 17, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Users\Shayan\AppData\Roaming\Anki2\addons21\255272392\libs\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

**Comment by olyaee** [comment]
Hi @ShayanKhodadadian, 

Unfortunatelly, I don't have a Windows machine and won't be able to fix the bug. However, I've open-sourced the source could. Would you like to contribute and fix the issue on Windows? here is the repo

https://github.com/olyaee/intelli-deck-addon
